### ISSUE TITLE
Missing Main Class in dart_duckdb Plugin Causes Errors on macOS and Windows Targets

### ISSUE THREAD

**Issue by Tinnci** [TigerEyeLabs/duckdb-dart#1]
# Missing Main Class in `dart_duckdb` Plugin Causes Errors on macOS and Windows Targets

**Description:**

I encountered an issue while integrating the `dart_duckdb` plugin (version 1.0.1) into my Flutter project. Although the project targets macOS and Windows, the build fails due to errors related to the Android package, specifically referencing a missing main class.

On **macOS**, after deleting the `/android` directory, the build succeeds. However, on **Windows**, this workaround does not resolve the issue, and I still encounter a build failure due to a missing directory for Windows.

Here are the error messages I encountered:

- **macOS Error:**

    ```
    The plugin `dart_duckdb` doesn't have a main class defined in:
    - /Users/<username>/.pub-cache/hosted/pub.dev/dart_duckdb-1.0.1/android/src/main/java/com/tigereye/duckdb_libs/DuckdbLibsPlugin.java
    - /Users/<username>/.pub-cache/hosted/pub.dev/dart_duckdb-1.0.1/android/src/main/kotlin/com/tigereye/duckdb_libs/DuckdbLibsPlugin.kt
    
    This is likely due to an incorrect `androidPackage: com.tigereye.duckdb_libs` or `mainClass` entry in the plugin's `pubspec.yaml`.
    ```

- **Windows Error:**

    ```
    The plugin `dart_duckdb` doesn't have a main class defined in:
    C:\Users\<username>\AppData\Local\Pub\Cache\hosted\pub.dev\dart_duckdb-1.0.1\android\src\main\java\com\tigereye\duckdb_libs\DuckdbLibsPlugin.java or
    C:\Users\<username>\AppData\Local\Pub\Cache\hosted\pub.dev\dart_duckdb-1.0.1\android\src\main\kotlin\com\tigereye\duckdb_libs\DuckdbLibsPlugin.kt.

    This is likely due to an incorrect `androidPackage: com.tigereye.duckdb_libs` or `mainClass` entry in the plugin's `pubspec.yaml`.
    ```

Additionally, on **Windows**, I encountered the following error:

```
CMake Error at flutter/generated_plugins.cmake:15 (add_subdirectory):
  add_subdirectory given source "flutter/ephemeral/.plugin_symlinks/dart_duckdb/windows" which is not an
  existing directory.
```

This suggests that the plugin lacks a properly configured Windows directory, leading to a failure when building on Windows.

**Steps to Reproduce:**

1. Create a Flutter project targeting both macOS and Windows.
2. Add the `dart_duckdb` plugin as a dependency.
3. On macOS:
   - Remove the `/android` directory from the project.
   - The build should succeed after this workaround.
4. On Windows:
   - Removing the `/android` directory does not resolve the issue.
   - Attempt to build the project and observe the error regarding the missing Windows directory.

**Expected Behavior:**

The plugin should provide proper configuration for macOS and Windows builds. Specifically:

- **macOS** should not require the removal of the `/android` directory to build successfully.
- **Windows** should have a properly configured Windows directory to avoid build errors related to missing platform-specific files.

**System Information:**

- **macOS:**

    ```
    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, 3.24.0, on macOS 15.0 darwin-x64, locale zh-Hans-CN)
    [✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [!] Xcode - develop for iOS and macOS (Xcode 16.0)
        ✗ Unable to get list of installed Simulator runtimes.
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 2024.1)
    [✓] VS Code (version 1.92.2)
    [✓] Connected device (3 available)
    [✓] Network resources

    ! Doctor found issues in 1 category.
    ```

- **Windows:**

    ```
    Doctor summary (to see all details, run flutter doctor -v):
    [√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [版本 10.0.27686.1000], locale zh-CN)
    [√] Windows Version (Installed version of Windows is version 10 or higher)
    [!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
        X cmdline-tools component is missing
        X Android license status unknown.
    [√] Chrome - develop for the web
    [√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.6)
    [!] Android Studio (not installed)
    [√] VS Code (version 1.92.2)
    [√] Connected device (3 available)
    [√] Network resources

    ! Doctor found issues in 2 categories.
    ```

**Test Code:**

```dart
import 'package:flutter/material.dart';
import 'package:dart_duckdb/dart_duckdb.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'DuckDB Test App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _queryResult = "Running DuckDB queries...";

  @override
  void initState() {
    super.initState();
    _runDatabaseTest();
  }

  Future<void> _runDatabaseTest() async {
    try {
      // Open DuckDB in-memory database
      final database = duckdb.open(":memory:");
      final connection = duckdb.connect(database);

      // Create a table and insert data
      connection.execute('''
        CREATE TABLE users (id INTEGER, name VARCHAR, age INTEGER);
        INSERT INTO users VALUES (1, 'Alice', 30), (2, 'Bob', 25);
      ''');

      // Query users older than 28
      final result = connection.query("SELECT * FROM users WHERE age > 28").fetchAll();

      // Format results for display
      final resultString = result.map((row) => "ID: ${row[0]}, Name: ${row[1]}, Age: ${row[2]}").join("\n");

      // Update UI
      setState(() {
        _queryResult = resultString;
      });

      // Dispose connection and database
      connection.dispose();
      database.dispose();
    } catch (e) {
      setState(() {
        _queryResult = "Error: $e";
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("DuckDB Test App"),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Text(
            _queryResult,
            textAlign: TextAlign.center,
            style: const TextStyle(fontSize: 16),
          ),
        ),
      ),
    );
  }
}
```

**Additional Context:**

While the plugin appears to work on macOS after removing the `/android` directory, the Windows build fails due to a missing directory for Windows in the plugin setup. The issue seems to stem from incomplete platform-specific configurations for non-Android platforms. The macOS workaround is not ideal, and the Windows build does not proceed at all without further adjustments.

Please investigate the plugin configuration for macOS and Windows to ensure it is correctly set up for multi-platform projects without requiring Android-specific checks for these platforms.

Thank you for your assistance in resolving this issue!

**Comment by aprock** [comment]
Thank you for bringing this to our attention. I'll dig into this and see what is going on.

**Comment by aprock** [comment]
the binaries were missing from pub.dev. the fix is to download them during the build phase, given pub.dev's filesize restriction.

**Comment by Tinnci** [comment]
> the binaries were missing from pub.dev. the fix is to download them during the build phase, given pub.dev's filesize restriction.

Thanks a lot for fixing the issue with the missing binaries. Really appreciate the quick help! Best of luck with the project moving forward.
